//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMVCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        public int BRANCH_NUMBER { get; set; }
        public string BRANCH_DESCRIPTION { get; set; }
    }
}
