//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMVCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public int DEPARTMENT_NUMBER { get; set; }
        public string DEPARTMENT_DESCRIPTION { get; set; }
        public string UNDERWRITING_FLAG { get; set; }
        public string CLAIMS_FLAG { get; set; }
        public string PROGRAM_FLAG { get; set; }
        public Nullable<int> DEDUCTIBLE_BILLING_FLAG { get; set; }
        public Nullable<int> PROFITCENTERKEY { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AccountingGroupTypeKey { get; set; }
        public Nullable<bool> CreateNewSubmissions { get; set; }
    }
}
