//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMVCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCalendarYear
    {
        public int EmployeeCalendarYearKey { get; set; }
        public int CalendarYearKey { get; set; }
        public int Emp_Record_Number { get; set; }
        public Nullable<decimal> StartOfYearPTOHours { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
