//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMVCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.EmployeeCalendarYears = new HashSet<EmployeeCalendarYear>();
            this.EmployeeStatusHistories = new HashSet<EmployeeStatusHistory>();
            this.Employee_OrgUnit_XRef = new HashSet<Employee_OrgUnit_XRef>();
            this.EmployeePersonalContacts = new HashSet<EmployeePersonalContact>();
            this.EMPLOYEE1 = new HashSet<EMPLOYEE>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.EMPLOYEE11 = new HashSet<EMPLOYEE>();
            this.EMPLOYEEs1 = new HashSet<EMPLOYEE>();
            this.EMPLOYEE12 = new HashSet<EMPLOYEE>();
            this.EMPLOYEEs2 = new HashSet<EMPLOYEE>();
        }
    
        public int EMP_RECORD_NUMBER { get; set; }
        public string EMP_USER_PROFILE { get; set; }
        public string EMP_LAST_NAME { get; set; }
        public string EMP_ACTIVE_CODE { get; set; }
        public Nullable<int> EMP_EXTENSION { get; set; }
        public string EMP_FIRST_NAME { get; set; }
        public string EMP_MIDDLE_NAME { get; set; }
        public string EMP_PREFIX { get; set; }
        public Nullable<int> EMP_BRANCH_NUMBER { get; set; }
        public Nullable<int> EMP_DEPARTMENT_NUMBER { get; set; }
        public string EMP_EMAIL_ADDRESS { get; set; }
        public string EMP_FAXNUMBER { get; set; }
        public Nullable<decimal> PaymentAuthority { get; set; }
        public Nullable<int> EmployeeTypeKey { get; set; }
        public bool IsExempt { get; set; }
        public bool IsOnPayroll { get; set; }
        public Nullable<int> DefaultUnderwriter { get; set; }
        public bool IsExecutive { get; set; }
        public string Signature { get; set; }
        public Nullable<bool> AllowCompressed { get; set; }
        public Nullable<System.DateTime> CompressedStatusDate { get; set; }
        public bool WorkOtherDepartmentTasks { get; set; }
        public Nullable<decimal> IndemnityReserveAuthority { get; set; }
        public Nullable<decimal> ExpenseReserveAuthority { get; set; }
        public string Initials { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string STATE_ABBREVIATION { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<EmployeeCalendarYear> EmployeeCalendarYears { get; set; }
        public virtual ICollection<EmployeeStatusHistory> EmployeeStatusHistories { get; set; }
        public virtual ICollection<Employee_OrgUnit_XRef> Employee_OrgUnit_XRef { get; set; }
        public virtual ICollection<EmployeePersonalContact> EmployeePersonalContacts { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEE1 { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEE11 { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs1 { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEE12 { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs2 { get; set; }
    }
}
