//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMVCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePersonalContact
    {
        public int EmployeePersonalContactKey { get; set; }
        public int Emp_Record_Number { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> LocationSkey { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
