//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMVCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_OrgUnit_XRef
    {
        public int EmployeeOrgUnitXrefID { get; set; }
        public int EMP_RECORD_NUMBER { get; set; }
        public int OrgUnitID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
