//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateMVCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeStatusHistory
    {
        public int EmployeeStatusHistoryKey { get; set; }
        public int EmployeeStatusKey { get; set; }
        public int Emp_Record_Number { get; set; }
        public System.DateTime EffectiveDate { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
    }
}
